"""Fix sqlalchemy

Revision ID: 00d1803b3268
Revises: f22fd1d7576d
Create Date: 2024-11-03 18:26:52.305183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00d1803b3268'
down_revision: Union[str, None] = 'f22fd1d7576d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
