"""Update tables

Revision ID: 0fc77fe64e97
Revises: 670371b7e2ca
Create Date: 2024-11-03 13:37:08.350585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fc77fe64e97'
down_revision: Union[str, None] = '670371b7e2ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tgusers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tasks', sa.Column('tguser_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'tgusers', ['tguser_id'], ['id'])
    op.create_unique_constraint(None, 'users', ['login'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'tguser_id')
    op.drop_table('tgusers')
    # ### end Alembic commands ###
