"""add nickname column

Revision ID: ed6dc17ffa41
Revises: e87690c07a31
Create Date: 2024-11-03 18:05:25.798857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed6dc17ffa41'
down_revision: Union[str, None] = 'e87690c07a31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tgusers', sa.Column('nickname', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tgusers', 'nickname')
    # ### end Alembic commands ###
