"""add tg_id column

Revision ID: f22fd1d7576d
Revises: ed6dc17ffa41
Create Date: 2024-11-03 18:12:10.847744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f22fd1d7576d'
down_revision: Union[str, None] = 'ed6dc17ffa41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tgusers', sa.Column('tg_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tgusers', 'tg_id')
    # ### end Alembic commands ###
